# Copyright 2019-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

    commands:
      - echo "Install Prequisites"
      - echo $CROSS_ACCOUNT_ROLE
      - echo $TF_WOKLOAD_REPO_URL
      - echo $PATH
      - apt-get update
      - apt-get install zip
      - pip install --upgrade pip
      - mkdir ~/bin
      - wget https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip
      - unzip terraform_0.13.4_linux_amd64.zip
      - mv terraform /codebuild/user/bin
      - echo $PATH
      - terraform version
      - pip install terraform-compliance==1.3.4
      - git version
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - printenv
      - ls -R
  build:
    commands:
      - ./remote_pull_repo.sh $CROSS_ACCOUNT_ROLE $COMPLIANCE_REPO_URL
      - ./compliance-check.sh
reports:
  tf-compliance-html-report:
    base-directory: 'reports'
    files:
      - 'test.json'
    file-format: CucumberJson
artifacts:
  files:
    - 'reports/**/*'
  name: tf-compliance-report-$(date +%Y-%m-%d)
